### ISSUE TITLE
Material Design theme

### ISSUE THREAD

**Issue by Sabuto** [wieslawsoltes/NodeEditor#12]
Hey I love this project!

Would you consider making a theme for material design instead of fluent?

**Comment by wieslawsoltes** [comment]
Material theme is not available is Avalonia itself.

Anyway fluent theme should really work with any theme, the naming is bit misleading.

**Comment by Sabuto** [comment]
It is available for avalonia https://github.com/AvaloniaCommunity/material.avalonia

I tried to use it instead of the fluent but it doesnt work, but i suppose if the rest of my app is available in material and then the pan and zoom is fluent would be ok :)

**Comment by wieslawsoltes** [comment]
@Sabuto The material theme is missing some controls e.g. Label https://github.com/AvaloniaCommunity/Material.Avalonia/issues/123

**Comment by wieslawsoltes** [comment]
I got it working here: https://github.com/wieslawsoltes/NodeEditor/tree/Material https://github.com/wieslawsoltes/NodeEditor/commit/576d05b26da4bdd3bd70382319dbf4181502b618

**Comment by Sabuto** [comment]
oh awesome ill clone it and have a play :) thanks!
