### ISSUE TITLE
Add Name property for pins

### ISSUE THREAD

**Issue by furesoft** [wieslawsoltes/NodeEditor#17]
Add Names as Tooltips to Pins to identify for user and later for execution

**Comment by wieslawsoltes** [comment]
Will add in next release.

**Comment by wieslawsoltes** [comment]
@furesoft 

https://user-images.githubusercontent.com/2297442/144568011-173616a5-56bf-4f1d-8cf2-10feec0969e2.mp4

part of https://github.com/wieslawsoltes/NodeEditor/pull/15
