### ISSUE TITLE
Can't connect nodes if they added with code

### ISSUE THREAD

**Issue by furesoft** [wieslawsoltes/NodeEditor#18]
If I add standard nodes on load I cannot connect these nodes to other nodes

**Comment by wieslawsoltes** [comment]
The Pin has to have set correct Parent to connect property and update it's position.

https://github.com/wieslawsoltes/NodeEditor/blob/92a492dd08b2817f22658378d9ae975a71752055/src/NodeEditorAvalonia.ReactiveUI/ViewModels/NodeViewModelExtensions.cs#L13
