### ISSUE TITLE
Allow only one connection mode for Pin

### ISSUE THREAD

**Issue by furesoft** [wieslawsoltes/NodeEditor#19]
Enable to disallow multiple connections on pin.

**Comment by wieslawsoltes** [comment]
Added new API
https://github.com/wieslawsoltes/NodeEditor/blob/fc99c03a33cfde3dc4742f4d3cb48785aaa9644b/src/NodeEditorAvalonia.Model/IPin.cs#L12
https://github.com/wieslawsoltes/NodeEditor/blob/fc99c03a33cfde3dc4742f4d3cb48785aaa9644b/src/NodeEditorAvalonia.Model/IDrawingNode.cs#L15

**Comment by wieslawsoltes** [comment]
Added 
https://github.com/wieslawsoltes/NodeEditor/blob/dfa64dff672a681f9749ce6161553b1e18122445/src/NodeEditorAvalonia.Model/IDrawingNode.cs#L13
and
https://github.com/wieslawsoltes/NodeEditor/blob/dfa64dff672a681f9749ce6161553b1e18122445/src/NodeEditorAvalonia.Model/IDrawingNode.cs#L14
will be in next beta release.
