### ISSUE TITLE
Drop nodes on mouse position

### ISSUE THREAD

**Issue by furesoft** [wieslawsoltes/NodeEditor#23]
I have resized my canvas to 10000x7500, when I drop nodes on it the nodes are hided in the lower right corner. So it would be a great improvement to drop the node where the mouse position is

**Comment by wieslawsoltes** [comment]
Aren't nodes dropped on mouse position right now?

https://github.com/wieslawsoltes/NodeEditor/blob/58170442d6642b2bf75e568af81835695d5c8970/src/NodeEditorAvalonia/Behaviors/DrawingDropHandler.cs#L49

**Comment by furesoft** [comment]
![image](https://user-images.githubusercontent.com/4117602/145602653-c2dee0ac-b838-40c9-ba9a-b8a495e29ec5.png)

no. I have drop in the middle of the canvas

**Comment by furesoft** [comment]
hmm try to use my canvas dimension: 10000x7500

**Comment by wieslawsoltes** [comment]
Still can not repro:

https://user-images.githubusercontent.com/2297442/145604142-fc5beab3-bf57-40ef-95cd-15e77818f3e0.mp4

**Comment by furesoft** [comment]
https://user-images.githubusercontent.com/4117602/145606256-f2ec0540-ce80-4bc5-9c34-4b90b24d91a9.mp4

This video covers drop and zoom problem

**Comment by wieslawsoltes** [comment]
Seems like you are missing background and maybe drop behavior can not get pointer input for correct position. Try adding background.

**Comment by furesoft** [comment]
I have Background="White" on NodeZoomBorder  but same result

**Comment by wieslawsoltes** [comment]
@furesoft Found the source of the issue, will fix in next release.

**Comment by wieslawsoltes** [comment]
Fix [`8e85023` (#26)](https://github.com/wieslawsoltes/NodeEditor/pull/26/commits/8e85023c7662e985bbfc66d296a8a8d889d84038)
