### ISSUE TITLE
Allow dynamic size of nodes

### ISSUE THREAD

**Issue by adirh3** [wieslawsoltes/NodeEditor#4]
Currently (from my understanding) you need to set static height/width for each node and their Pins.
This is OK for the start but, at least in my scenario each node will have different size depending on user input.
I am sure I can just change these properties as I get user input, but it would be less optimal.
Thanks!

**Comment by kevin100702** [comment]
I want to drag the mouse on the four corners to change the size of the Node, can you guide me how to do it?

**Comment by wieslawsoltes** [comment]
> I want to drag the mouse on the four corners to change the size of the Node, can you guide me how to do it?

Not implemented yet

**Comment by AbdalaMask** [comment]
How to save the page to Xaml

**Comment by AbdalaMask** [comment]
How to save the page to Xaml

**Comment by wieslawsoltes** [comment]
> How to save the page to Xaml

Please keep issues on topic, saving to xaml is not a feature, you define nodes as view models and those can be serialized.
