### ISSUE TITLE
 How to save the page to Xaml

### ISSUE THREAD

**Issue by AbdalaMask** [wieslawsoltes/NodeEditor#42]
How to save the page to Xaml

**Comment by wieslawsoltes** [comment]
Serialize your view model https://github.com/wieslawsoltes/NodeEditor/blob/e18cd6ed9326b05f73ff7517e54e9976a3558e5f/samples/NodeEditor.Base/ViewModels/EditorViewModel.cs#L171

**Comment by AbdalaMask** [comment]
How does the component zoom in and out?

**Comment by wieslawsoltes** [comment]
> How does the component zoom in and out?

Please check https://github.com/wieslawsoltes/NodeEditor/tree/main/samples/NodeEditor.Base is has all possible functionality.

https://github.com/wieslawsoltes/NodeEditor/blob/bbae56902ceddc715be0659daf9c1c7b9564ef73/samples/NodeEditor.Base/Views/EditorView.axaml#L31
