### ISSUE TITLE
how fix this 

### ISSUE THREAD

**Issue by AbdalaMask** [wieslawsoltes/NodeEditor#46]
![image](https://user-images.githubusercontent.com/37013638/203928098-f0457370-170d-4e99-8593-dfdd00037375.png)

**Comment by wieslawsoltes** [comment]
Please provide full stack trace and xaml to repro.

**Comment by wieslawsoltes** [comment]
Please also update title to be more detailed

**Comment by AbdalaMask** [comment]
Event Type Moniker	Event	Time	Duration	Thread
	Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll ("Unable to cast object of type 'NodeEditor.ViewModels.NodeViewModel' to type 'NodeEditor.Model.IPin'.") Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll ("Unable to cast object of type 'NodeEditor.ViewModels.NodeViewModel' to type 'NodeEditor.Model.IPin'.") Hyperlink: Activate Historical Debugging	5.00s		[8608] Main Thread

**Comment by AbdalaMask** [comment]
One of the important things in this project is to enlarge the node and reduce it
Please attention

**Comment by wieslawsoltes** [comment]
> Event Type Moniker Event Time Duration Thread Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll ("Unable to cast object of type 'NodeEditor.ViewModels.NodeViewModel' to type 'NodeEditor.Model.IPin'.") Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll ("Unable to cast object of type 'NodeEditor.ViewModels.NodeViewModel' to type 'NodeEditor.Model.IPin'.") Hyperlink: Activate Historical Debugging 5.00s [8608] Main Thread

Please show complete xaml and code

**Comment by AbdalaMask** [comment]
![image](https://user-images.githubusercontent.com/37013638/204016690-e1b28bf0-e693-4045-b07f-9f63b03bf04b.png)
![image](https://user-images.githubusercontent.com/37013638/204016732-0512127f-4e31-4418-8f3a-12ae72533c93.png)
Try there

**Comment by AbdalaMask** [comment]
One of the important things in this project is to enlarge the node and reduce it
Please attention
