### ISSUE TITLE
Hanging up in WASM/mobile builds?

### ISSUE THREAD

**Issue by atcarter714** [wieslawsoltes/NodeEditor#51]
We tried adding the node editor into a new Avalonia template but it keeps stalling/hanging before the splash screen & page load. And I figured this is likely due to some kind of mismatch or incompatibility of versions. Anyone else had this issue or know how to point us in the right direction? We were using the last 11.0.0 preview

**Comment by wieslawsoltes** [comment]
Fixed in master branch
