### ISSUE TITLE
Release 11.1.0 has failed to push

### ISSUE THREAD

**Issue by IvanJosipovic** [wieslawsoltes/NodeEditor#61]
Hey,

it looks like the last release 11.1.0 needs a kick :)

Thank you!

**Comment by wieslawsoltes** [comment]
Well 11.1 broke completely NodeEditor so need to fix but its really bad :(

**Comment by wieslawsoltes** [comment]
Working on fix here https://github.com/wieslawsoltes/NodeEditor/pull/62

**Comment by IvanJosipovic** [comment]
@wieslawsoltes, thank you!
